export const locationData = {
  provinces: ['Zamboanga del Sur'],
  cities: {
    'Zamboanga del Sur': ['Pagadian City', 'Aurora', 'Bayog', 'Dimataling', 'Dinas', 'Dumalinao', 'Dumingag', 'Guipos', 'Josefina', 'Kumalarang', 'Labangan', 'Lakewood', 'Lapuyan', 'Mahayag', 'Margosatubig', 'Midsalip', 'Molave', 'Pitogo', 'Ramon Magsaysay', 'San Miguel', 'San Pablo', 'Sominot', 'Tabina', 'Tambulig', 'Tigbao', 'Tukuran', 'Vincenzo A. Sagun'],
  },
  barangays: {
    'Pagadian City': [
      "Alegria",
      "Balangasan",
      "Balintawak",
      "Baloyboan",
      "Banale",
      "Bogo",
      "Bomba",
      "Buenavista",
      "Bulatok",
      "Bulawan",
      "Dampalan",
      "Danlugan",
      "Dao",
      "Datagan",
      "Deborok",
      "Ditoray",
      "Dumagoc",
      "Gatas",
      "Gubac",
      "Gubang",
      "Kagawasan",
      "Kahayagan",
      "Kalasan",
      "Kawit",
      "La Suerte",
      "Lala",
      "Lapidian",
      "Lenienza",
      "Lizon Valley",
      "Lourdes",
      "Lower Sibatang",
      "Lumad",
      "Lumbia",
      "Macasing",
      "Manga",
      "Muricay",
      "Napolan",
      "Palpalan",
      "Pedulonan",
      "Poloyagan",
      "San Francisco",
      "San Jose",
      "San Pedro",
      "Santa Lucia",
      "Santa Maria",
      "Santiago",
      "Santo Niño",
      "Tawagan Sur",
      "Tiguma",
      "Tuburan",
      "Tulangan",
      "Tulawas",
      "Upper Sibatang",
      "White Beach"
    ],
  },
};